name: Deploy Serverless Application

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Set Serverless Access Key
        run: echo "SLS_ACCESS_KEY=${{ secrets.SLS_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Verify Access Key is Set
        run: echo $SLS_ACCESS_KEY

      - name: Deploy to AWS using Serverless Framework
        run: yarn serverless deploy --debug
        env:
          SLS_ACCESS_KEY: ${{ secrets.SLS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PRISMA_CLI_BINARY_TARGETS: rhel-openssl-3.0.x