name: Deploy Serverless Application

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Generate Prisma Client
        run: yarn prisma generate
        env:
          PRISMA_CLI_BINARY_TARGETS: native,rhel-openssl-1.0.x

      - name: Deploy to AWS using Serverless Framework
        run: yarn serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PRISMA_CLI_BINARY_TARGETS: native,rhel-openssl-1.0.x  